# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActorConf_Properties.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActorConf_Properties.proto',
  package='XlsxConvert',
  syntax='proto3',
  serialized_options=_b('\252\002\032XlsxConvert.Auto.ActorConf'),
  serialized_pb=_b('\n\x1a\x41\x63torConf_Properties.proto\x12\x0bXlsxConvert\"o\n\x1b\x41\x63torConf_Properties_Record\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02hp\x18\x03 \x01(\x05\x12\n\n\x02mp\x18\x04 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x05 \x01(\x05\x12\x0e\n\x06\x64\x65\x66\x65nd\x18\x06 \x01(\x05\"T\n\x1a\x41\x63torConf_Properties_Sheet\x12\x36\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32(.XlsxConvert.ActorConf_Properties_RecordB\x1d\xaa\x02\x1aXlsxConvert.Auto.ActorConfb\x06proto3')
)




_ACTORCONF_PROPERTIES_RECORD = _descriptor.Descriptor(
  name='ActorConf_Properties_Record',
  full_name='XlsxConvert.ActorConf_Properties_Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='XlsxConvert.ActorConf_Properties_Record.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='XlsxConvert.ActorConf_Properties_Record.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp', full_name='XlsxConvert.ActorConf_Properties_Record.hp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mp', full_name='XlsxConvert.ActorConf_Properties_Record.mp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack', full_name='XlsxConvert.ActorConf_Properties_Record.attack', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defend', full_name='XlsxConvert.ActorConf_Properties_Record.defend', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=154,
)


_ACTORCONF_PROPERTIES_SHEET = _descriptor.Descriptor(
  name='ActorConf_Properties_Sheet',
  full_name='XlsxConvert.ActorConf_Properties_Sheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='XlsxConvert.ActorConf_Properties_Sheet.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=240,
)

_ACTORCONF_PROPERTIES_SHEET.fields_by_name['data'].message_type = _ACTORCONF_PROPERTIES_RECORD
DESCRIPTOR.message_types_by_name['ActorConf_Properties_Record'] = _ACTORCONF_PROPERTIES_RECORD
DESCRIPTOR.message_types_by_name['ActorConf_Properties_Sheet'] = _ACTORCONF_PROPERTIES_SHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActorConf_Properties_Record = _reflection.GeneratedProtocolMessageType('ActorConf_Properties_Record', (_message.Message,), {
  'DESCRIPTOR' : _ACTORCONF_PROPERTIES_RECORD,
  '__module__' : 'ActorConf_Properties_pb2'
  # @@protoc_insertion_point(class_scope:XlsxConvert.ActorConf_Properties_Record)
  })
_sym_db.RegisterMessage(ActorConf_Properties_Record)

ActorConf_Properties_Sheet = _reflection.GeneratedProtocolMessageType('ActorConf_Properties_Sheet', (_message.Message,), {
  'DESCRIPTOR' : _ACTORCONF_PROPERTIES_SHEET,
  '__module__' : 'ActorConf_Properties_pb2'
  # @@protoc_insertion_point(class_scope:XlsxConvert.ActorConf_Properties_Sheet)
  })
_sym_db.RegisterMessage(ActorConf_Properties_Sheet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
