# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: XlsxRecordIndex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='XlsxRecordIndex.proto',
  package='XlsxConvert',
  syntax='proto3',
  serialized_options=_b('\252\002\031XlsxConvert.Auto.Indexers'),
  serialized_pb=_b('\n\x15XlsxRecordIndex.proto\x12\x0bXlsxConvert\"\x1f\n\rXlsxRecordIds\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\xa8\x01\n\x18XlsxRecordGroupIndexDict\x12\x41\n\x06values\x18\x01 \x03(\x0b\x32\x31.XlsxConvert.XlsxRecordGroupIndexDict.ValuesEntry\x1aI\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.XlsxConvert.XlsxRecordIds:\x02\x38\x01\"\xad\x01\n\x15XlsxRecordIndexesDict\x12>\n\x06values\x18\x01 \x03(\x0b\x32..XlsxConvert.XlsxRecordIndexesDict.ValuesEntry\x1aT\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.XlsxConvert.XlsxRecordGroupIndexDict:\x02\x38\x01\x42\x1c\xaa\x02\x19XlsxConvert.Auto.Indexersb\x06proto3')
)




_XLSXRECORDIDS = _descriptor.Descriptor(
  name='XlsxRecordIds',
  full_name='XlsxConvert.XlsxRecordIds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='XlsxConvert.XlsxRecordIds.values', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=69,
)


_XLSXRECORDGROUPINDEXDICT_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='XlsxConvert.XlsxRecordGroupIndexDict.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='XlsxConvert.XlsxRecordGroupIndexDict.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='XlsxConvert.XlsxRecordGroupIndexDict.ValuesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=240,
)

_XLSXRECORDGROUPINDEXDICT = _descriptor.Descriptor(
  name='XlsxRecordGroupIndexDict',
  full_name='XlsxConvert.XlsxRecordGroupIndexDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='XlsxConvert.XlsxRecordGroupIndexDict.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_XLSXRECORDGROUPINDEXDICT_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=240,
)


_XLSXRECORDINDEXESDICT_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='XlsxConvert.XlsxRecordIndexesDict.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='XlsxConvert.XlsxRecordIndexesDict.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='XlsxConvert.XlsxRecordIndexesDict.ValuesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=416,
)

_XLSXRECORDINDEXESDICT = _descriptor.Descriptor(
  name='XlsxRecordIndexesDict',
  full_name='XlsxConvert.XlsxRecordIndexesDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='XlsxConvert.XlsxRecordIndexesDict.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_XLSXRECORDINDEXESDICT_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=416,
)

_XLSXRECORDGROUPINDEXDICT_VALUESENTRY.fields_by_name['value'].message_type = _XLSXRECORDIDS
_XLSXRECORDGROUPINDEXDICT_VALUESENTRY.containing_type = _XLSXRECORDGROUPINDEXDICT
_XLSXRECORDGROUPINDEXDICT.fields_by_name['values'].message_type = _XLSXRECORDGROUPINDEXDICT_VALUESENTRY
_XLSXRECORDINDEXESDICT_VALUESENTRY.fields_by_name['value'].message_type = _XLSXRECORDGROUPINDEXDICT
_XLSXRECORDINDEXESDICT_VALUESENTRY.containing_type = _XLSXRECORDINDEXESDICT
_XLSXRECORDINDEXESDICT.fields_by_name['values'].message_type = _XLSXRECORDINDEXESDICT_VALUESENTRY
DESCRIPTOR.message_types_by_name['XlsxRecordIds'] = _XLSXRECORDIDS
DESCRIPTOR.message_types_by_name['XlsxRecordGroupIndexDict'] = _XLSXRECORDGROUPINDEXDICT
DESCRIPTOR.message_types_by_name['XlsxRecordIndexesDict'] = _XLSXRECORDINDEXESDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XlsxRecordIds = _reflection.GeneratedProtocolMessageType('XlsxRecordIds', (_message.Message,), {
  'DESCRIPTOR' : _XLSXRECORDIDS,
  '__module__' : 'XlsxRecordIndex_pb2'
  # @@protoc_insertion_point(class_scope:XlsxConvert.XlsxRecordIds)
  })
_sym_db.RegisterMessage(XlsxRecordIds)

XlsxRecordGroupIndexDict = _reflection.GeneratedProtocolMessageType('XlsxRecordGroupIndexDict', (_message.Message,), {

  'ValuesEntry' : _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _XLSXRECORDGROUPINDEXDICT_VALUESENTRY,
    '__module__' : 'XlsxRecordIndex_pb2'
    # @@protoc_insertion_point(class_scope:XlsxConvert.XlsxRecordGroupIndexDict.ValuesEntry)
    })
  ,
  'DESCRIPTOR' : _XLSXRECORDGROUPINDEXDICT,
  '__module__' : 'XlsxRecordIndex_pb2'
  # @@protoc_insertion_point(class_scope:XlsxConvert.XlsxRecordGroupIndexDict)
  })
_sym_db.RegisterMessage(XlsxRecordGroupIndexDict)
_sym_db.RegisterMessage(XlsxRecordGroupIndexDict.ValuesEntry)

XlsxRecordIndexesDict = _reflection.GeneratedProtocolMessageType('XlsxRecordIndexesDict', (_message.Message,), {

  'ValuesEntry' : _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _XLSXRECORDINDEXESDICT_VALUESENTRY,
    '__module__' : 'XlsxRecordIndex_pb2'
    # @@protoc_insertion_point(class_scope:XlsxConvert.XlsxRecordIndexesDict.ValuesEntry)
    })
  ,
  'DESCRIPTOR' : _XLSXRECORDINDEXESDICT,
  '__module__' : 'XlsxRecordIndex_pb2'
  # @@protoc_insertion_point(class_scope:XlsxConvert.XlsxRecordIndexesDict)
  })
_sym_db.RegisterMessage(XlsxRecordIndexesDict)
_sym_db.RegisterMessage(XlsxRecordIndexesDict.ValuesEntry)


DESCRIPTOR._options = None
_XLSXRECORDGROUPINDEXDICT_VALUESENTRY._options = None
_XLSXRECORDINDEXESDICT_VALUESENTRY._options = None
# @@protoc_insertion_point(module_scope)
