#!/usr/bin/env python
# -*- encoding: utf-8 -*-

# ------------------------------------------------------------
#       @file  template.py
#      @brief  Lua file template.
#
#     @author  VyronLee, lwz_jz@hotmail.com
#   @Modified  2019-09-29 14:44
#  @Copyright  Copyright (c) 2019, VyronLee
# ============================================================

lua_file_template = '''------------------------------------------------------------
--      @file %s
--     @brief Auto generated by XlsxConverter, DONT EDIT IT!
--    @author VyronLee(lwz_jz@hotmail.com)
-- @Copyright Copyright(c) 2019, Apache-2.0
------------------------------------------------------------
local keys = {
%s}

local mt = {
\t__index = function(t,k)
\t\treturn keys[k] and t[keys[k].index]
\tend,
}
local __mt = setmetatable

local conf = {}

conf.data = {
%s}

conf.indexes = {
%s}

conf.parseArgs = function(self, ...)
\tlocal keys, values = {}, {}
\tlocal args = { ... }
\tfor idx,val in ipairs(args) do
\t\tif idx %% 2 == 1 then
\t\t\tkeys[#keys + 1] = val
\t\telse
\t\t\tvalues[#values + 1] = val
\t\tend
\tend
\treturn keys, values
end

conf.getData = function(self, ...)
\tlocal keys, values = self:parseArgs(...)
\tlocal keyHash = table.concat(keys, '-')
\tlocal valueHash = table.concat(values, '-')
\tlocal keyMap = self.indexes[keyHash] or {}
\tlocal valueMap = keyMap[valueHash] or {}
\tlocal ret  = {}
\tfor idx,val in ipairs(valueMap) do
\t\tret[#ret + 1] = self.data[val]
\tend
\treturn ret
end

return conf'''
